In [1]:
library(data.table)
library(nycflights13)
library(DT)

In [2]:
options(repr.matrix.max.rows=20, repr.matrix.max.cols=30)

In [3]:
head(airlines)

  carrier name
1 9E      Endeavor Air Inc.
2 AA      American Airlines Inc.
3 AS      Alaska Airlines Inc.
4 B6      JetBlue Airways
5 DL      Delta Air Lines Inc.
6 EV      ExpressJet Airlines Inc.

In [4]:
flights

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 1     1   517      515             2         830      819
2      2013 1     1   533      529             4         850      830
3      2013 1     1   542      540             2         923      850
4      2013 1     1   544      545            -1        1004     1022
5      2013 1     1   554      600            -6         812      837
6      2013 1     1   554      558            -4         740      728
7      2013 1     1   555      600            -5         913      854
8      2013 1     1   557      600            -3         709      723
9      2013 1     1   557      600            -3         838      846
10     2013 1     1   558      600            -2         753      745
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
336767 2013 9     30  2240     2250           -10       2347        7
336768 2013 9     30  2241     2246            -5       2345        1
336769 2013 9     30  2307     2255            12       2359     2358
336770 2013 9     30  2349     2359           -10        325      350
336771 2013 9     30    NA     1842            NA         NA     2019
336772 2013 9     30    NA     1455            NA         NA     1634
336773 2013 9     30    NA     2200            NA         NA     2312
336774 2013 9     30    NA     1210            NA         NA     1330
336775 2013 9     30    NA     1159            NA         NA     1344
336776 2013 9     30    NA      840            NA         NA     1020
       arr_delay carrier flight tailnum origin dest air_time distance hour
1       11       UA      1545   N14228  EWR    IAH  227      1400     5
2       20       UA      1714   N24211  LGA    IAH  227      1416     5
3       33       AA      1141   N619AA  JFK    MIA  160      1089     5
4      -18       B6       725   N804JB  JFK    BQN  183      1576     5
5      -25       DL       461   N668DN  LGA    ATL  116       762     6
6       12       UA      1696   N39463  EWR    ORD  150       719     5
7       19       B6       507   N516JB  EWR    FLL  158      1065     6
8      -14       EV      5708   N829AS  LGA    IAD   53       229     6
9       -8       B6        79   N593JB  JFK    MCO  140       944     6
10       8       AA       301   N3ALAA  LGA    ORD  138       733     6
⋮      ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮
336767 -20       B6      2002   N281JB  JFK    BUF   52       301     22
336768 -16       B6       486   N346JB  JFK    ROC   47       264     22
336769   1       B6       718   N565JB  JFK    BOS   33       187     22
336770 -25       B6       745   N516JB  JFK    PSE  196      1617     23
336771  NA       EV      5274   N740EV  LGA    BNA   NA       764     18
336772  NA       9E      3393   NA      JFK    DCA   NA       213     14
336773  NA       9E      3525   NA      LGA    SYR   NA       198     22
336774  NA       MQ      3461   N535MQ  LGA    BNA   NA       764     12
336775  NA       MQ      3572   N511MQ  LGA    CLE   NA       419     11
336776  NA       MQ      3531   N839MQ  LGA    RDU   NA       431      8
       minute time_hour
1      15     2013-01-01 05:00:00
2      29     2013-01-01 05:00:00
3      40     2013-01-01 05:00:00
4      45     2013-01-01 05:00:00
5       0     2013-01-01 06:00:00
6      58     2013-01-01 05:00:00
7       0     2013-01-01 06:00:00
8       0     2013-01-01 06:00:00
9       0     2013-01-01 06:00:00
10      0     2013-01-01 06:00:00
⋮      ⋮      ⋮
336767 50     2013-09-30 22:00:00
336768 46     2013-09-30 22:00:00
336769 55     2013-09-30 22:00:00
336770 59     2013-09-30 23:00:00
336771 42     2013-09-30 18:00:00
336772 55     2013-09-30 14:00:00
336773  0     2013-09-30 22:00:00
336774 10     2013-09-30 12:00:00
336775 59     2013-09-30 11:00:00
336776 40     2013-09-30 08:00:00

In [5]:
flights <- copy(flights)
setDT(flights)

In [6]:
str(flights)

Classes ‘data.table’ and 'data.frame':	336776 obs. of  19 variables:
 $ year          : int  2013 2013 2013 2013 2013 2013 2013 2013 2013 2013 ...
 $ month         : int  1 1 1 1 1 1 1 1 1 1 ...
 $ day           : int  1 1 1 1 1 1 1 1 1 1 ...
 $ dep_time      : int  517 533 542 544 554 554 555 557 557 558 ...
 $ sched_dep_time: int  515 529 540 545 600 558 600 600 600 600 ...
 $ dep_delay     : num  2 4 2 -1 -6 -4 -5 -3 -3 -2 ...
 $ arr_time      : int  830 850 923 1004 812 740 913 709 838 753 ...
 $ sched_arr_time: int  819 830 850 1022 837 728 854 723 846 745 ...
 $ arr_delay     : num  11 20 33 -18 -25 12 19 -14 -8 8 ...
 $ carrier       : chr  "UA" "UA" "AA" "B6" ...
 $ flight        : int  1545 1714 1141 725 461 1696 507 5708 79 301 ...
 $ tailnum       : chr  "N14228" "N24211" "N619AA" "N804JB" ...
 $ origin        : chr  "EWR" "LGA" "JFK" "JFK" ...
 $ dest          : chr  "IAH" "IAH" "MIA" "BQN" ...
 $ air_time      : num  227 227 160 183 116 150 158 53 140 138 ...
 $ distance      : num  1400 1416 1089 1576 762 ...
 $ hour          : num  5 5 5 5 6 5 6 6 6 6 ...
 $ minute        : num  15 29 40 45 0 58 0 0 0 0 ...
 $ time_hour     : POSIXct, format: "2013-01-01 05:00:00" "2013-01-01 05:00:00" ...
 - attr(*, ".internal.selfref")=<externalptr>

## filtering flights which flies more than 80 minutes and delayed

In [7]:
flights [ air_time > 80 & arr_delay > 0 ]

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 1     1   517      515             2        830      819
2      2013 1     1   533      529             4        850      830
3      2013 1     1   542      540             2        923      850
4      2013 1     1   554      558            -4        740      728
5      2013 1     1   555      600            -5        913      854
6      2013 1     1   558      600            -2        753      745
7      2013 1     1   558      600            -2        924      917
8      2013 1     1   559      600            -1        941      910
9      2013 1     1   600      600             0        837      825
10     2013 1     1   602      605            -3        821      805
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
102421 2013 9     30  2104     2019            45       2304     2240
102422 2013 9     30  2104     2030            34       2205     2150
102423 2013 9     30  2110     2055            15         51     2359
102424 2013 9     30  2114     2025            49       2304     2228
102425 2013 9     30  2119     2005            74       2310     2212
102426 2013 9     30  2147     2137            10         30       27
102427 2013 9     30  2207     2140            27       2257     2250
102428 2013 9     30  2211     2059            72       2339     2242
102429 2013 9     30  2233     2113            80        112       30
102430 2013 9     30  2235     2001           154         59     2249
       arr_delay carrier flight tailnum origin dest air_time distance hour
1      11        UA      1545   N14228  EWR    IAH  227      1400     5
2      20        UA      1714   N24211  LGA    IAH  227      1416     5
3      33        AA      1141   N619AA  JFK    MIA  160      1089     5
4      12        UA      1696   N39463  EWR    ORD  150       719     5
5      19        B6       507   N516JB  EWR    FLL  158      1065     6
6       8        AA       301   N3ALAA  LGA    ORD  138       733     6
7       7        UA       194   N29129  JFK    LAX  345      2475     6
8      31        AA       707   N3DUAA  LGA    DFW  257      1389     6
9      12        MQ      4650   N542MQ  LGA    ATL  134       762     6
10     16        MQ      4401   N730MQ  LGA    DTW  105       502     6
⋮      ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮
102421  24       EV      4333   N11109  EWR    TUL  154      1215     20
102422  15       WN       382   N7741C  LGA    MDW  105       725     20
102423  52       B6      1205   N517JB  JFK    PDX  361      2454     20
102424  36       EV      4348   N11184  EWR    MSP  145      1008     20
102425  58       EV      4321   N17984  EWR    MCI  147      1092     20
102426   3       B6      1371   N627JB  LGA    FLL  139      1076     21
102427   7       MQ      3660   N532MQ  LGA    BNA   97       764     21
102428  57       EV      4672   N12145  EWR    STL  120       872     20
102429  42       UA       471   N578UA  EWR    SFO  318      2565     21
102430 130       B6      1083   N804JB  JFK    MCO  123       944     20
       minute time_hour
1      15     2013-01-01 05:00:00
2      29     2013-01-01 05:00:00
3      40     2013-01-01 05:00:00
4      58     2013-01-01 05:00:00
5       0     2013-01-01 06:00:00
6       0     2013-01-01 06:00:00
7       0     2013-01-01 06:00:00
8       0     2013-01-01 06:00:00
9       0     2013-01-01 06:00:00
10      5     2013-01-01 06:00:00
⋮      ⋮      ⋮
102421 19     2013-09-30 20:00:00
102422 30     2013-09-30 20:00:00
102423 55     2013-09-30 20:00:00
102424 25     2013-09-30 20:00:00
102425  5     2013-09-30 20:00:00
102426 37     2013-09-30 21:00:00
102427 40     2013-09-30 21:00:00
102428 59     2013-09-30 20:00:00
102429 13     2013-09-30 21:00:00
102430  1     2013-09-30 20:00:00

## J operation. Showing only arrive delays and the speeds of planes type of miles per hour.

In [8]:
flights [, .(arr_delay, speedmilehour = distance / ((air_time %/% 100) + ((air_time %% 100)/60)))]

       arr_delay speedmilehour
1       11       571.4286
2       20       577.9592
3       33       544.5000
4      -18       661.2587
5      -25       601.5789
6       12       392.1818
7       19       541.5254
8      -14       259.2453
9       -8       566.4000
10       8       448.7755
⋮      ⋮         ⋮
336767 -20       347.3077
336768 -16       337.0213
336769   1       340.0000
336770 -25       621.9231
336771  NA             NA
336772  NA             NA
336773  NA             NA
336774  NA             NA
336775  NA             NA
336776  NA             NA

## J operation. Adding speeds, kilometers per hour.

In [9]:
flights [, speedkmh:= (distance * 1.609344) / ((air_time %/% 100) + ((air_time %% 100)/60))]
flights [, .(speedkmh)]
flights

       speedkmh
1       919.6251
2       930.1351
3       876.2878
4      1064.1928
5       968.1475
6       631.1555
7       871.5007
8       417.2148
9       911.5324
10      722.2342
⋮      ⋮
336767  558.9376
336768  542.3832
336769  547.1770
336770 1000.8882
336771        NA
336772        NA
336773        NA
336774        NA
336775        NA
336776        NA

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 1     1   517      515             2         830      819
2      2013 1     1   533      529             4         850      830
3      2013 1     1   542      540             2         923      850
4      2013 1     1   544      545            -1        1004     1022
5      2013 1     1   554      600            -6         812      837
6      2013 1     1   554      558            -4         740      728
7      2013 1     1   555      600            -5         913      854
8      2013 1     1   557      600            -3         709      723
9      2013 1     1   557      600            -3         838      846
10     2013 1     1   558      600            -2         753      745
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
336767 2013 9     30  2240     2250           -10       2347        7
336768 2013 9     30  2241     2246            -5       2345        1
336769 2013 9     30  2307     2255            12       2359     2358
336770 2013 9     30  2349     2359           -10        325      350
336771 2013 9     30    NA     1842            NA         NA     2019
336772 2013 9     30    NA     1455            NA         NA     1634
336773 2013 9     30    NA     2200            NA         NA     2312
336774 2013 9     30    NA     1210            NA         NA     1330
336775 2013 9     30    NA     1159            NA         NA     1344
336776 2013 9     30    NA      840            NA         NA     1020
       arr_delay carrier flight tailnum origin dest air_time distance hour
1       11       UA      1545   N14228  EWR    IAH  227      1400     5
2       20       UA      1714   N24211  LGA    IAH  227      1416     5
3       33       AA      1141   N619AA  JFK    MIA  160      1089     5
4      -18       B6       725   N804JB  JFK    BQN  183      1576     5
5      -25       DL       461   N668DN  LGA    ATL  116       762     6
6       12       UA      1696   N39463  EWR    ORD  150       719     5
7       19       B6       507   N516JB  EWR    FLL  158      1065     6
8      -14       EV      5708   N829AS  LGA    IAD   53       229     6
9       -8       B6        79   N593JB  JFK    MCO  140       944     6
10       8       AA       301   N3ALAA  LGA    ORD  138       733     6
⋮      ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮
336767 -20       B6      2002   N281JB  JFK    BUF   52       301     22
336768 -16       B6       486   N346JB  JFK    ROC   47       264     22
336769   1       B6       718   N565JB  JFK    BOS   33       187     22
336770 -25       B6       745   N516JB  JFK    PSE  196      1617     23
336771  NA       EV      5274   N740EV  LGA    BNA   NA       764     18
336772  NA       9E      3393   NA      JFK    DCA   NA       213     14
336773  NA       9E      3525   NA      LGA    SYR   NA       198     22
336774  NA       MQ      3461   N535MQ  LGA    BNA   NA       764     12
336775  NA       MQ      3572   N511MQ  LGA    CLE   NA       419     11
336776  NA       MQ      3531   N839MQ  LGA    RDU   NA       431      8
       minute time_hour           speedkmh
1      15     2013-01-01 05:00:00  919.6251
2      29     2013-01-01 05:00:00  930.1351
3      40     2013-01-01 05:00:00  876.2878
4      45     2013-01-01 05:00:00 1064.1928
5       0     2013-01-01 06:00:00  968.1475
6      58     2013-01-01 05:00:00  631.1555
7       0     2013-01-01 06:00:00  871.5007
8       0     2013-01-01 06:00:00  417.2148
9       0     2013-01-01 06:00:00  911.5324
10      0     2013-01-01 06:00:00  722.2342
⋮      ⋮      ⋮                   ⋮
336767 50     2013-09-30 22:00:00  558.9376
336768 46     2013-09-30 22:00:00  542.3832
336769 55     2013-09-30 22:00:00  547.1770
336770 59     2013-09-30 23:00:00 1000.8882
336771 42     2013-09-30 18:00:00        NA
336772 55     2013-09-30 14:00:00        NA
336773  0     2013-09-30 22:00:00        NA
336774 10     2013-09-30 12:00:00        NA
336775 59     2013-09-30 11:00:00        NA
336776 40     2013-09-30 08:00:00        NA

## By operation. Adding minimum and maximum department time of every day in the year.

In [10]:
flights [, .(min_dep_time = min(dep_time, na.rm=T), max_dep_time = max(dep_time, na.rm=T)), by = c("month","day") ]

    month day min_dep_time max_dep_time
1   1      1  517          2356
2   1      2   42          2354
3   1      3   32          2349
4   1      4   25          2358
5   1      5   14          2357
6   1      6   16          2355
7   1      7   49          2359
8   1      8  454          2351
9   1      9    2          2252
10  1     10    3          2320
⋮   ⋮     ⋮   ⋮            ⋮
356 9     21    8          2306
357 9     22  518          2350
358 9     23  455          2342
359 9     24  455          2348
360 9     25  451          2358
361 9     26  451          2349
362 9     27  453          2346
363 9     28  451          2351
364 9     29  521          2356
365 9     30  453          2349